# Generated by Django 3.0.5 on 2020-04-30 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=128, null=True)),
                ('employee_position', models.CharField(choices=[('manager', 'manager'), ('asst_manager', 'asst_manager'), ('cashier', 'cashier'), ('loan_approval', 'loan_approval')], max_length=128, null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('others', 'others')], max_length=128, null=True)),
                ('marital_status', models.CharField(choices=[('Unmarried', 'Unmarried'), ('married', 'married'), ('others', 'others')], max_length=128, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
