# Generated by Django 3.0.5 on 2020-05-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='country',
            field=models.CharField(default='india', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='pincode',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
